# Generated by Django 5.1.2 on 2024-11-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wastes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(max_length=8)),
                ('photo', models.ImageField(upload_to='cars')),
                ('validated', models.BooleanField(default=False)),
            ],
        ),
    ]
