# Generated by Django 5.1.2 on 2024-11-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_val', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wastes',
            new_name='Waste',
        ),
    ]
