# Generated by Django 5.1.2 on 2024-11-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_val', '0002_rename_wastes_waste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste',
            name='category',
            field=models.TextField(max_length=9),
        ),
    ]
