# Generated by Django 5.1.2 on 2024-12-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_val', '0003_alter_waste_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waste',
            name='category',
        ),
        migrations.AlterField(
            model_name='waste',
            name='photo',
            field=models.ImageField(upload_to='test'),
        ),
    ]
